### ISSUE TITLE
Conti playout does not load and does not actually playout any files.

### ISSUE THREAD

**Issue by LZNetwork-Main** [nebulabroadcast/nebula-tutorial#1]
I have installed the docker version of Nebula from this repo.
The installation went fine as well as importing and converting assets - this is all working fine.
The problem is, when I add an asset - be it filler, movie or anything - to the scheduler, the rundown gets stuck on this:
![Screenshot 2023-03-18 185501](https://user-images.githubusercontent.com/96541915/226125746-77609358-031a-4fac-9685-a72f03765bd7.png)
I tried to look at the hls stream as well, just to be sure that it is not a bug with the CUR: and NXT: counters, but the hls feed is also just black.
Also tried the take button, it did not work, it just threw an error into the logs "Unable to take. Playlist is empty.".
Also tried to change the run mode, the same thing but with a different error "AttributeError: 'OperationsRequestModel' object has no attribute 'data'".

I am attaching all logs, as well as a screenshot. Please help me with this.

[server-logs.txt](https://github.com/nebulabroadcast/nebula-tutorial/files/11009239/server-logs.txt)
[client-logs.txt](https://github.com/nebulabroadcast/nebula-tutorial/files/11009240/client-logs.txt)

**Comment by martastain** [comment]
Thanks for the report. It should be fixed now, just run `make update` to fetch the newest images.

![image](https://user-images.githubusercontent.com/5007200/226558599-fe3a0ade-5893-403b-8c4a-71d4afc3c6b2.png)

- In order to start the playback, double-click the first item of the playlist (or any item) to let the controller know, where you want to start

- Triple-check that `storage/hls` directory exists - conti does not check that and simply crashes if it cannot store data.
